"""
Django settings for HumanTalent project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gtzw_am76hix#m2-l@jwuu%pytg-#^l50*-z3)dl6jarck-af0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admins.apps.AdminsConfig',
    'users.apps.UsersConfig',
    'company.apps.CompanyConfig',
    'HojaVida.apps.HojavidaConfig',
    'perfil_user.apps.PerfilUserConfig',
    'requisicion.apps.RequisicionConfig',
    'axes',
    'sweetify',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'HumanTalent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
   'axes.backends.AxesBackend',
   'django.contrib.auth.backends.ModelBackend',
]

WSGI_APPLICATION = 'HumanTalent.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "HumanTalent",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "localhost",
        "PORT": "3307",
    }
}
# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT= BASE_DIR
STATICFILES_DIRS=['HumanTalent/static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
APPEND_SLASH = False


AUTH_USER_MODEL = 'admins.Myuser'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_SSL = False
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "haroldsabogal48@gmail.com"
EMAIL_HOST_PASSWORD = "ypad bcfq hkuy ndda"
DEFAULT_FROM_EMAIL = "haroldsabogal48@gmail.com"

AXES_FAILURE_LIMIT: 3 # INTENTOS PERMITIDOS
AXES_COOLOFF_TIME: 0.02 # TIEMPO DE BLOQUE EN HORAS
AXES_RESET_ON_SUCCESS = True # RESETEO DE INTENTOS

AXES_LOCKOUT_TEMPLATE = 'Account_lockout.html' # TEMPLATE
AXES_LOCKOUT_URL = 'lockout' # URL DEL TEMPLATE
#AXES_LOCKOUT_PARAMETERS = ["username", "user_agent"]
AXES_LOCK_OUT_AT_FAILURE = True # ! OPCION DE BLOQUEO
AXES_ENABLE_ACCESS_FAILURE_LOG = True

JAZZMIN_SETTINGS = {
    "site_title": "Human Talent Admin",
    "site_header": "Human Talent",
    "site_brand": "Human Talent",
    "site_logo": "/img/logo.png",
    "copyright": "Human Talent SENA",
    "login_logo_dark": None,
    "login_logo": None,
    "welcome_sign": "Welcome a Human Talen Administrator",
    # "user_avatar": None,  # Nombre del campo en el modelo de usuario que contiene el avatar ImageField/URLField/Charfield o un callable que recibe el usuario
    "custom_css": "css/admin.css",
    "search_model": ["admins.Myuser"],
    }

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
}

MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"

SWEETIFY_SWEETALERT_LIBRARY = 'sweetalert2'
