# Generated by Django 5.0.3 on 2024-03-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('Cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('Ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('Fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('Registro', models.DateTimeField(auto_now_add=True)),
                ('Redes_sociales', models.URLField(blank=True, null=True)),
                ('Fondo', models.ImageField(blank=True, null=True, upload_to='fondos/')),
                ('Foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_normal')),
            ],
        ),
    ]
