# Generated by Django 5.0.1 on 2024-03-15 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('direccion', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('codigo_cno', models.IntegerField()),
                ('nombre_cargo', models.CharField(max_length=50)),
                ('educacion', models.CharField(choices=[('Basica primaria', 'Basica primaria'), ('Basica secundaria', 'Basica secundaria'), ('Tecnico', 'Tecnico'), ('Tecnologo', 'Tecnologo'), ('Pregrado', 'Pregrado'), ('Posgrado', 'Posgrado')], default='Basica primaria', max_length=50)),
                ('experiencia_laboral', models.CharField(max_length=100)),
                ('habilidades', models.CharField(max_length=120)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=20)),
                ('forma_pago', models.CharField(choices=[('Mensual', 'Mensual'), ('Quincenal', 'Quincenal'), ('Semanal', 'Semanal'), ('Bisemanal', 'Bisemanal')], default='Mensual', max_length=20)),
                ('jornada_laboral', models.CharField(max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('Indefinido', 'Indefinido'), ('Termino fijo', 'Termino fijo'), ('Practicas', 'Practicas'), ('Aprendizaje', 'Aprendizaje')], default='Indefinido', max_length=50)),
                ('descripcion', models.TextField()),
                ('id_myuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisicion',
                'verbose_name_plural': 'Requisiciones',
                'db_table': 'Requisicion',
            },
        ),
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educacion', models.IntegerField()),
                ('experiencia', models.IntegerField()),
                ('habilidades', models.IntegerField()),
                ('ubicacion', models.IntegerField()),
                ('total', models.IntegerField()),
                ('id_myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisicion.requisicion')),
            ],
            options={
                'verbose_name': 'Ponderacion',
                'verbose_name_plural': 'Ponderaciones',
                'db_table': 'Ponderacion',
            },
        ),
    ]
